### PR TITLE
Update callbacks to support Hedwig 1.0.0

### PR DESCRIPTION
**Pull request by stevegrossi**
Hedwig 1.0 brought [some API changes to the `Hedwig.Robot` interface](https://github.com/hedwig-im/hedwig/blob/bd00ab94c7a1d9550fa65305d99ea0f936394a8b/CHANGELOG.md#v100-2016-11-20), notably:

> - `after_connect/1` is now `handle_connect/1`. See the docs for details.
> - Adapters should now call `Hedwig.Robot.handle_in/2` rather than `handle_message` for incoming messages. See the docs for details.

This PR simply updates those callbacks in `hedwig_flowdock` to the new interface. 

### Caveat

This may not be the full story, at least in my demo chatbot. With these changes I'm no longer seeing errors about `handle_message` not being defined, but the robot doesn't respond to messages, either. I've confirmed with logging in `lib/hedwig_flowdock.ex` that the adapter receives messages from Flowdock:

screen shot 2016-12-23 at 6 13 47 am

screen shot 2016-12-23 at 6 12 45 am

(To be clear: the bot no longer responds with "pong" here.)

Where it immediately dispatches them to `Hedwig.Robot.handle_in`, so it may be that the problem is on `Hedwig`'s end or in my configuration thereof, though I can confirm that the bot responds as expected in the `Console` adapter.

Anyway, I'm continuing to work on this but wanted to share my progress thus far as a PR, hoping that it may be useful.

### CODE REVIEW

**Comment by stevegrossi** [comment]
> Where it immediately dispatches them to `Hedwig.Robot.handle_in`, so it may be that the problem is on Hedwig's end or in my configuration thereof

After further debugging, `Hedwig.Robot.handle_in` appears to work just fine. The `%Hedwig.Message{}` is dispatched to each responder and I've confirmed that they receive the message:

```ruby
respond ~r/ping$/i, msg do
  IO.puts("Hedwig.Responders.Ping RESPONDING") # This happens
  reply msg, "pong"
end
```

The problem appears to be in how hedwig_flowdock handles `reply` under hedwig 1.0. As best I can tell:

1. Responders call `Hedwig.Responder.reply`
2. This delegates to `Hedwig.Robot.reply`
3. That delegates to `@adapter.reply`
4. Which calls `GenServer.cast(pid, {:reply, msg})`
5. At this point, the hedwig-flowdock adapter takes over and [handles that cast](https://github.com/supernullset/hedwig_flowdock/blob/master/lib/hedwig_flowdock.ex#L45):

```elixir
def handle_cast({:reply, %{user: user, text: text} = msg}, %{rest_conn: r_conn} = state) do
   IO.puts("GOT handle_cast with :reply") # This never happens
```

However step 5 appears never to happen. I'll continue looking into why.

**Comment by stevegrossi** [comment]
Figured it out! It looks like the latest version of hedwig is expecting a `robot` key—which hedwig_flowdock isn't setting—on the `%Hedwig.Message{}` struct when replying (so `robot` being `nil` caused the issue above).

The [relevant line](https://github.com/hedwig-im/hedwig/blob/eeb70eba7730d554da188b9b5da6e20804cdb25a/lib/hedwig/responder.ex#L81) from the hedwig library:

```elixir
def reply(%Hedwig.Message{robot: robot} = msg, text) do
  # …
```

Which I've fixed by adding `robot: robot` here: https://github.com/stevegrossi/hedwig_flowdock/commit/61587631b442c96d9f0db9280bfe39a230557379 and added to this PR. So as far as I can tell, this PR is sufficient to get hedwig-flowdock working with Hedwig 1.0. I'll be happy to follow your instructions to get it merged here, and will rely on [my fork](https://github.com/stevegrossi/hedwig_flowdock) in the meantime.

**Comment by stevegrossi** [comment]
One additional change: have the adapter send itself `:connection_ready` on boot.

It looks like `hedwig_flowdock` was prepared to handle `:connection_ready`, but never receiving it. I’m not sure if Hedwig used to send this message, but it doesn’t anymore. And in Hedwig’s own Console and Test adapters, it expects the adapter to send itself this message on boot, so I do likewise in the Flowdock adapter here.

**Comment by supernullset** [comment]
@stevegrossi First off, let me apologize for my gross negligence on addressing this. I took a "new" job right around the time you opened this, and I have been...swamped.

Changes look great! Thank you so much for making this change!

**Comment by stevegrossi** [comment]
No apologies necessary! I'm grateful for your work on the flowdock adapter and glad I could contribute even a little. I hope the new gig's going well 👍

**Pull request merged**
